### ISSUE TITLE
Busca de clientes com acentos

### ISSUE THREAD

**Issue by megabga** [brunoguerra/guara#3]
Busca com acentos não estão funcionando.

**Comment by felipedaraujo** [comment]
As seguinte linhas devem ser acrescentadas no arquivo database.yml do
projeto guara

collate: pt_BR.UTF8
ctype: pt_BR.UTF8

Em 9 de janeiro de 2013 17:49, Bruno Guerra notifications@github.comescreveu:

> Busca com acentos não estão funcionando.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/woese/guara/issues/3.

## 

Att,
Felipe de Araújo

Trainee Software Development - Woese
Graduando em Análise de Sistemas - Estácio Ceará
+55 85 87814364 | skype: felipe.daraujo

“Nenhum de nós é tão bom, quanto todos nós juntos” - Ray Kroc - Fundador
McDonald´s

**Comment by megabga** [comment]
Caracteres maiúsculos e minúsculos não são diferenciados
